import os
import pickle
import re
from rapidfuzz import fuzz
from rapidfuzz.distance import Levenshtein

# --- CONFIGURATION ---
ROOT_DIRECTORIES = ["D:/progmars/Documents", "D:/progmars/Foto&video" ]  # Folder you want to index
INDEX_FILE = "file_index.pkl"      # Where to save the index data
EXTENSIONS = "txt,md,doc,docx,pdf,mp3,mp4,avi,mov,mkv,jpg,jpeg,png,bmp"


class FileSearchEngine:

    def __init__(self):
        # Each item dict: {path, stem, tokens}
        self.index = []


    def scan_and_index(self):
        found_items = []

        # EXTENSIONS are guaranteed lowercase, no spaces, no dots
        allowed_exts = {'.' + ext for ext in EXTENSIONS.split(',')}

        for dir in ROOT_DIRECTORIES:
            print(f"Indexing {dir}...")
            for root, _, files in os.walk(dir):
                for file in files:
                    # Check file extension case-insensitively
                    _, ext = os.path.splitext(file)
                    if ext.lower() in allowed_exts:
                        full_path = os.path.join(root, file)
                        name = os.path.basename(full_path)
                        stem, _ = os.path.splitext(name)
                        # Precompute tokens and clean extension
                        ext_clean = ext.lower().lstrip('.')
                        token_splitter = re.compile(r"[^a-z0-9]+")
                        tokens = [t for t in token_splitter.split(stem.lower()) if t]
                        if not tokens:
                            tokens = [stem.lower()]
                        # Include extension as a normal token (no separate handling later)
                        if ext_clean and ext_clean not in tokens:
                            tokens.append(ext_clean)
                        found_items.append({
                            'path': full_path,
                            'stem': stem.lower(),
                            'tokens': tokens,
                        })

        self.index = found_items

        self.save_index()


    @staticmethod
    def find_match(text, indexed_items):
        # the code generated by AI, no warranties

        # Normalize query
        query = str(text).lower().strip()

        if not indexed_items:
            return None

        # Token-based matching: split stems on non-alphanumeric boundaries
        token_splitter = re.compile(r"[^a-z0-9]+")
        q_tokens = [t for t in token_splitter.split(query) if len(t) > 1]
        qlen = len(query)
        ranked = []

        for item in indexed_items:
            stem = item['stem']
            tokens = item['tokens']

            best_token_score = -1
            best_token_dist = 999
            best_token_len = 0
            contains_substring = False

            # Count how many query tokens appear as substrings in any token (including extension token)
            token_hits = 0
            for qt in q_tokens:
                if any(qt in tok for tok in tokens):
                    token_hits += 1

            for tok in tokens:                   
                dist = Levenshtein.distance(query, tok)
                sim = 1.0 - Levenshtein.normalized_distance(query, tok)

                # Exact substring containment in token
                if query in tok:
                    contains_substring = True
                    # Perfect containment base score
                    # Score boosted for containment; shorter edit distance wins
                    score = 100 - dist * 10 + int(sim * 10)
                else:
                    # Normalize distance by max length
                    rel = dist / max(len(tok), qlen)
                    score = int(round((1 - rel) * 70 + sim * 30))

                # Prefer lower distance, then higher score, then token length close to query
                if (dist < best_token_dist or
                    (dist == best_token_dist and score > best_token_score) or
                    (dist == best_token_dist and score == best_token_score and abs(len(tok) - qlen) < abs(best_token_len - qlen))):
                    best_token_score = score
                    best_token_dist = dist
                    best_token_len = len(tok)

            # Fallback base fuzzy ratio for entire stem (helps break ties among similar tokens across stems)
            stem_base = fuzz.partial_ratio(query, stem)
            # Aggregate final ordering criteria
            ranked.append((
                item['path'],
                contains_substring,
                best_token_dist,
                best_token_score,
                stem_base,
                abs(best_token_len - qlen),
                token_hits,
            ))

        if not ranked:
            return None

        # Sort priority:
        # 1) higher number of query token hits in tokens
        # 2) token substring containment of full query
        # 3) lowest edit distance
        # 4) higher token score
        # 5) stem_base fuzzy score
        # 6) token length proximity to query
        ranked.sort(key=lambda x: (
            -x[6],              # token_hits desc
            0 if x[1] else 1,   # contains_substring
            x[2],               # edit distance asc
            -x[3],              # token score desc
            -x[4],              # stem_base desc
            x[5]                # len proximity asc
        ))

        best_opt, contains_substring, dist, token_score, stem_base, len_prox, token_hits = ranked[0]
        final_score = min(100, max(token_score, stem_base))
        return (best_opt, final_score)


    def save_index(self):
        with open(INDEX_FILE, 'wb') as f:
            pickle.dump({'items': self.index}, f)


    def load_index(self):
        if os.path.exists(INDEX_FILE):
            with open(INDEX_FILE, 'rb') as f:
                data = pickle.load(f)
                self.index = data.get('items', [])
            return True
        return False


    def search(self, query):       
        q = str(query).strip().lower()
        if not q:
            return []

        best_match = FileSearchEngine.find_match(q, self.index)

        return best_match


############################
# --- 1. INITIALIZE THE SINGLETON ENGINE ---
# for tool call
engine = FileSearchEngine()

